services:
  borg-backup-server:
    # it is a good practice to specify the image version instead of using "latest"
    image: ghcr.io/dusanmsk/borg-server:latest
    ports:
      # expose SSH port
      - "2224:22"
    environment:
      # specify SSH authorized keys
      AUTHORIZED_KEYS: |
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGy+6GovqH6qY4DGovHIaUiGXudHMulCMdrMN/LJf4Hg user@example1
        ssh-ed25519 AAAAC3NzaC2lZDI1NTE5AAAAIGy+7GovqH6qY4DGovHIaUiGXudHMulCMdrMN/LJf4Hg user@example2
        ssh-ed25519 AAAAC3NzaC3lZDI1NTE5AAAAIGy+8GovqH6qY4DGovHIaUiGXudHMulCMdrMN/LJf4Hg user@example3
    volumes:
      # specify path where borg backup will be stored
      - /tmp/test_backups:/borg
