name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [main]
    tags: ['v*'] # nepovinné: ak chceš buildovať pri vytváraní tagu

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image tag
        id: meta
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: server_image
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/borg-server:latest
            ghcr.io/${{ github.repository_owner }}/borg-server:${{ steps.meta.outputs.tag }}